"""added access token to plaid items

Revision ID: 934894c06740
Revises: bd00642b72a4
Create Date: 2025-05-25 00:33:52.208161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '934894c06740'
down_revision: Union[str, None] = 'bd00642b72a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_items', sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_items', 'access_token')
    # ### end Alembic commands ###
