"""added walmart receipt lookup

Revision ID: 94713e749146
Revises: 934894c06740
Create Date: 2025-05-26 23:15:43.825478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94713e749146'
down_revision: Union[str, None] = '934894c06740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walmart_receipt_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storeId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchaseDate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cardType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastFourDigits', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_status_code', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walmart_receipt_lookups')
    op.drop_table('plaid_webhooks')
    # ### end Alembic commands ###
