"""test

Revision ID: bd00642b72a4
Revises: c6739628db71
Create Date: 2025-05-25 00:27:30.518157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd00642b72a4'
down_revision: Union[str, None] = 'c6739628db71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_accounts',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mask', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('official_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('item_id', 'account_id')
    )
    op.create_table('plaid_balances',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('available', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('limit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plaid_items',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('available_products', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('billed_products', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('webhook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('plaid_transactions',
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_meta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pending', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pending_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaid_transactions')
    op.drop_table('plaid_items')
    op.drop_table('plaid_balances')
    op.drop_table('plaid_accounts')
    # ### end Alembic commands ###
